apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: devops-demo
    environment: staging
  name: devops-demo-staging
spec:
  rules:
    -
      host: staging.devops-hof.marrat.de
      http:
        paths:
          -
            backend:
              serviceName: devops-demo-staging
              servicePort: 3000
            path: /